### ISSUE TITLE
Not able to run the demo application

### ISSUE THREAD

**Issue by PrabakarKaruppasamy** [swimlane/ngx-graph#117]
Hi All,

I have saw this application in the below url.

[https://angularscript.com/graph-visualization-library-angular-ngx-graph/](Link).

But I am unable to run this facing below error.

`module.js:549
    throw err;
    ^

Error: Cannot find module '@angular-devkit/core'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\CECH0159\Desktop\Taken\Research\ngx-graph-master\node_modules\@angular-devkit\schematics\src\tree\virtual.js:10:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)`

**Comment by Stargator** [comment]
@PrabakarKaruppasamy Does [this example](https://stackblitz.com/edit/ngx-graph-simple-example) work for you?

**Comment by assafsun** [comment]
Another options are looking at the demo app or just downloading the source code and run "npm start"

**Comment by assafsun** [comment]
@PrabakarKaruppasamy I'm closing this issue for now. Let me know if the demo app still don't work for you and we will reopen it.
