### ISSUE TITLE
ngx-charts-dag doesnt works inside teradata covalent 

### ISSUE THREAD

**Issue by lcanaveral** [swimlane/ngx-graph#14]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
i am using a covatent teradata framework that has already installed ngx-charts, i added the npm for ngx-charts-dag and it pass the compilation process but it trigger the following error in the brownser:
```
DirectedGraphComponent.html:2 ERROR Error: Unable to resolve animation metadata node #undefined
    at visitAnimationNode (http://localhost:22222/vendor.bundle.js:120346:19)
    at AnimationAstBuilderVisitor.webpackJsonp.../../../animations/@angular/animations/browser.es5.js.AnimationAstBuilderVisitor.build (http://localhost:22222/vendor.bundle.js:120465:17)
    at buildAnimationAst (http://localhost:22222/vendor.bundle.js:120447:45)
    at InjectableAnimationEngine.webpackJsonp.../../../animations/@angular/animations/browser.es5.js.AnimationEngine.registerTrigger (http://localhost:22222/vendor.bundle.js:124008:41)
    at http://localhost:22222/vendor.bundle.js:212198:76
    at Array.forEach (native)
    at AnimationRendererFactory.webpackJsonp.../../../platform-browser/@angular/platform-browser/animations.es5.js.AnimationRendererFactory.createRenderer (http://localhost:22222/vendor.bundle.js:212198:27)
    at DebugRendererFactory2.webpackJsonp.../../../core/@angular/core.es5.js.DebugRendererFactory2.createRenderer (http://localhost:22222/vendor.bundle.js:169994:49)
    at createComponentView (http://localhost:22222/vendor.bundle.js:168598:56)
    at callWithDebugContext (http://localhost:22222/vendor.bundle.js:169962:42)
```

**Expected behavior**

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ngx-charts version:** 2

* **Angular version:** 4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by assafsun** [comment]
I'm closing this issue because this ngx-charts issue and not ngx-graph.
