### ISSUE TITLE
Angular 15 not supported

### ISSUE THREAD

**Issue by tzachs** [swimlane/ngx-graph#481]
**Describe the bug**
Angular 15 is not supported

**To Reproduce**
Upgrade to angular 15 using ng update

**Expected behavior**
All checks should pass OK.
Instead I'm getting ```npm ERR! Could not resolve dependency:
npm ERR! peer @angular/animations@"10.x || 11.x || 12.x || 13.x || 14.x" from @swimlane/ngx-graph@8.0.2```

**Screenshots**

**Demo**
No demo

**ngx-graph version**
`@swimlane/ngx-graph": "^8.0.2"`

**Additional context**

**Comment by tzachs** [comment]
For now, solved using `--force`

**Comment by Malwinderkaur** [comment]
Hi, when will this be available, I need the support for Angular 15, this is a blocker.

**Comment by kgish** [comment]
👍

**Comment by jurvi** [comment]
Related PR just got merged moments ago :) 

https://github.com/swimlane/ngx-graph/pull/486

**Comment by tzachs** [comment]
@jurvi can you please help us? I do see the commit in master but I don't see a new package with that commit.
How can we get the new package?

**Comment by kgish** [comment]
:+1:

**Comment by vdesai007** [comment]
When will the issue with Angular 15 be resolved. Currently it breaks on creating transition.

**Comment by jurvi** [comment]
> @jurvi can you please help us? I do see the commit in master but I don't see a new package with that commit. How can we get the new package?

I am not affiliated with the package in any way, just commenting things I see here. :) I am also eagerly waiting for the release.

@marjan-georgiev is the wielder of power here I believe.

**Comment by nawnitraman** [comment]
Angular 15 with 8.0.3 breaks with following error
```
ERROR TypeError: linkSelection.attr(...).transition is not a function
        at swimlane-ngx-graph.mjs:1785:22
        at Array.map (<anonymous>)
        at QueryList.map (core.mjs:22857:30)
        at GraphComponent.redrawLines (swimlane-ngx-graph.mjs:1779:27)
        at NodeComponent.updateGraph (node.component.ts:116:13)
        at node.component.ts:81:12
        at timer (zone.js:2405:41)
        at _ZoneDelegate.invokeTask (zone.js:406:31)
        at Object.onInvokeTask (core.mjs:26218:33)
        at _ZoneDelegate.invokeTask (zone.js:405:60)
```
It will be great, if someone can comment on 
- Is this issue tracked and any plan date for release ?

**Comment by Malwinderkaur** [comment]
> Angular 15 with 8.0.3 breaks with following error
> 
> ```
> ERROR TypeError: linkSelection.attr(...).transition is not a function
>         at swimlane-ngx-graph.mjs:1785:22
>         at Array.map (<anonymous>)
>         at QueryList.map (core.mjs:22857:30)
>         at GraphComponent.redrawLines (swimlane-ngx-graph.mjs:1779:27)
>         at NodeComponent.updateGraph (node.component.ts:116:13)
>         at node.component.ts:81:12
>         at timer (zone.js:2405:41)
>         at _ZoneDelegate.invokeTask (zone.js:406:31)
>         at Object.onInvokeTask (core.mjs:26218:33)
>         at _ZoneDelegate.invokeTask (zone.js:405:60)
> ```
> 
> It will be great, if someone can comment on
> 
> * Is this issue tracked and any plan date for release ?

Hi, workaround for this one is if you install d3-transition v1.1.3 in your project .

**Comment by nawnitraman** [comment]
> [Malwinderkaur](/Malwinderkaur)

Thanks for the workaround. It worked for us. Still waiting for proper version of ngx-graph for angular 15 compatibility.
Any update on the next release will be very helpful.

**Comment by nawnitraman** [comment]
@marjan-georgiev Can you please update us on the plan of fixing the angular 15 compatibility issue ?

**Comment by vdesai007** [comment]
@Malwinderkaur, @marjan-georgiev 

Any idea when can we have the angular 15 compatibility issue resolved. We cannot proceed with deployments on other environments until we have this issue resolved.

**Comment by Malwinderkaur** [comment]
Hi @vdesai007 I am also waiting for the release, I myself an not affiliated with this package

**Comment by conan747** [comment]
+1 Thanks!

**Comment by bsarkadi** [comment]
Hi guys,

Angular 16 is out now, so I think it would be worth looking into supporting it too if you plan on making a new release.

**Comment by Kr0san89** [comment]
Having it included into an Angular 16 Project, looks like it is working as before. So i think we could extend it.

**Comment by amelnikoff** [comment]
Ping! When to expect this change being released?
